### ISSUE TITLE
Renderer does not work on MacOS

### ISSUE THREAD

**Issue by Jackymancs4** [MarginallyClever/Robot-Overlord-App#151]
**Describe the bug**
On my Mac the renderer window stays empty, and the console is flooded with `Failed to compile vertex shader code: ERROR: 0:1: '' :  version '330' is not supported` error.
Tha app is unfortunately unusable.

**Platform (please complete the following information):**
 - Device: MacBook Pro (Retina, 13-inch, Early 2015) (x86)
2,7 GHz Intel Core i5 dual-core
Intel Iris Graphics 6100 1536 MB
 - OS: MacOS 12.6.6
 - App Version: 2.6.2

**Additional context**
I think you're hitting something like [Why is OpenGL giving me the error: ERROR: 0:1: '' : version '330' is not supported?](https://stackoverflow.com/questions/62990972/why-is-opengl-giving-me-the-error-error-01-version-330-is-not-support)

**Comment by i-make-robots** [comment]
Ugh... this was never a problem on the fixed function pipeline...

**Comment by Jackymancs4** [comment]
You really moves too fast xD Anyway:
```
java.lang.reflect.InvocationTargetException
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1369)
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1344)
        at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
        at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:98)
        at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:453)
        at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: com.jogamp.opengl.GLException: Caught GLException: Not a GL3 implementation on thread AWT-EventQueue-0
        at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
        at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
        at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
        at com.jogamp.opengl.awt.GLJPanel$OffscreenBackend.doPaintComponent(GLJPanel.java:2095)
        at com.jogamp.opengl.awt.GLJPanel.paintComponent(GLJPanel.java:569)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
        at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5311)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1657)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1632)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1570)
        at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
        at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5259)
        at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5069)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
        at com.jogamp.opengl.util.AWTAnimatorImpl$1.run(AWTAnimatorImpl.java:170)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.jogamp.opengl.GLException: Not a GL3 implementation
        at jogamp.opengl.gl4.GL4bcImpl.getGL3(GL4bcImpl.java:40454)
        at com.marginallyclever.robotoverlord.renderpanel.OpenGLRenderPanel$1.display(OpenGLRenderPanel.java:299)
        at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
        at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
        at com.jogamp.opengl.awt.GLJPanel$Updater.display(GLJPanel.java:1446)
        at com.jogamp.opengl.awt.GLJPanel$10.run(GLJPanel.java:1521)
        at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
        ... 31 more
java.lang.reflect.InvocationTargetException
```

OS: MacOS 12.6.6
Version: master

**Comment by Jackymancs4** [comment]
MacBook Pro (Retina, 13-inch, Early 2015) (x86)
2,7 GHz Intel Core i5 dual-core
Intel Iris Graphics 6100 1536 MB

**Comment by i-make-robots** [comment]
In the newest master I write some new information to the log file.  Please look for the line `c.m.r.renderpanel.OpenGLRenderPanel - OpenGL availability=` and send me everything that comes after that.

**Comment by Jackymancs4** [comment]
New log from master:
```
19:31:16.569 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.util.PropertiesFileHelper - robotoverlord.version=2.7.1
19:31:16.577 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - PROGRAM START
19:31:16.577 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - ------------------------------------------------
19:31:16.577 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - exec.mainClass = com.marginallyclever.robotoverlord.RobotOverlord
19:31:16.577 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.specification.version = 17
19:31:16.578 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - sun.jnu.encoding = UTF-8
19:31:16.578 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.class.path = /Users/jack/1Inspection/Robot-Overlord-App/.mvn/wrapper/maven-wrapper.jar
19:31:16.578 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.vm.vendor = Eclipse Adoptium
19:31:16.578 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - sun.arch.data.model = 64
19:31:16.578 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.vendor.url = https://adoptium.net/
19:31:16.578 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - user.timezone = Europe/Rome
19:31:16.578 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - maven.conf = /var/root/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1/conf
19:31:16.578 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.vm.specification.version = 17
19:31:16.578 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - os.name = Mac OS X
19:31:16.578 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - sun.java.launcher = SUN_STANDARD
19:31:16.578 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - user.country = IT
19:31:16.578 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - sun.boot.library.path = /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/lib
19:31:16.578 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - sun.java.command = org.apache.maven.wrapper.MavenWrapperMain exec:java -Dexec.mainClass=com.marginallyclever.robotoverlord.RobotOverlord
19:31:16.578 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - http.nonProxyHosts = local|*.local|169.254/16|*.169.254/16
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - jdk.debug = release
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - maven.home = /var/root/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - sun.cpu.endian = little
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - user.home = /var/root
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - user.language = en
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - sun.stderr.encoding = UTF-8
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.specification.vendor = Oracle Corporation
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.version.date = 2023-04-18
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.home = /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - file.separator = /
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.vm.compressedOopsMode = Zero based
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - line.separator = 

19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - sun.stdout.encoding = UTF-8
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.vm.specification.vendor = Oracle Corporation
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.specification.name = Java Platform API Specification
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - sun.management.compiler = HotSpot 64-Bit Tiered Compilers
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - ftp.nonProxyHosts = local|*.local|169.254/16|*.169.254/16
19:31:16.579 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.runtime.version = 17.0.7+7
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - user.name = root
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - path.separator = :
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - os.version = 12.6.6
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.runtime.name = OpenJDK Runtime Environment
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - file.encoding = UTF-8
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - guice.disable.misplaced.annotation.check = true
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.vm.name = OpenJDK 64-Bit Server VM
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.vendor.version = Temurin-17.0.7+7
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.vendor.url.bug = https://github.com/adoptium/adoptium-support/issues
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.io.tmpdir = /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.version = 17.0.7
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - user.dir = /Users/jack/1Inspection/Robot-Overlord-App
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - os.arch = x86_64
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - maven.multiModuleProjectDirectory = /Users/jack/1Inspection/Robot-Overlord-App
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.vm.specification.name = Java Virtual Machine Specification
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - native.encoding = UTF-8
19:31:16.580 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.library.path = /Users/jack/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
19:31:16.581 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.vm.info = mixed mode, sharing
19:31:16.581 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.vendor = Eclipse Adoptium
19:31:16.581 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.vm.version = 17.0.7+7
19:31:16.581 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - classworlds.conf = /var/root/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1/bin/m2.conf
19:31:16.581 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - sun.io.unicode.encoding = UnicodeBig
19:31:16.581 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - socksNonProxyHosts = local|*.local|169.254/16|*.169.254/16
19:31:16.581 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - java.class.version = 61.0
19:31:16.581 [com.marginallyclever.robotoverlord.RobotOverlord.main()] INFO  c.m.convenience.log.Log - ------------------------------------------------
19:31:20.088 [AWT-EventQueue-0] DEBUG c.m.robotoverlord.Project - Setting path to /var/root/RobotOverlord/Scene
19:31:20.111 [AWT-EventQueue-0] DEBUG c.m.r.s.translator.Translator - Translator start
19:31:20.117 [AWT-EventQueue-0] DEBUG c.m.r.s.translator.Translator - Default language = English
19:31:20.117 [AWT-EventQueue-0] DEBUG c.m.r.s.translator.Translator - Looking for languages path 'languages'.
19:31:20.117 [AWT-EventQueue-0] DEBUG c.m.r.s.translator.Translator - found.
19:31:20.118 [AWT-EventQueue-0] DEBUG c.m.r.s.translator.Translator - Looking for language files in /Users/jack/1Inspection/Robot-Overlord-App/target/classes/languages
19:31:20.122 [AWT-EventQueue-0] DEBUG c.m.r.s.translator.Translator - Looking at /Users/jack/1Inspection/Robot-Overlord-App/target/classes/languages
19:31:20.125 [AWT-EventQueue-0] DEBUG c.m.r.s.translator.Translator - Skipping, not an XML file.
19:31:20.126 [AWT-EventQueue-0] DEBUG c.m.r.s.translator.Translator - Looking at /Users/jack/1Inspection/Robot-Overlord-App/target/classes/languages/english.xml
19:31:20.126 [AWT-EventQueue-0] DEBUG c.m.r.s.translator.Translator - Found /Users/jack/1Inspection/Robot-Overlord-App/target/classes/languages/english.xml
19:31:20.440 [AWT-EventQueue-0] INFO  c.m.robotoverlord.RobotOverlord - buildMainFrame()
19:31:20.446 [AWT-EventQueue-0] INFO  c.m.robotoverlord.MainFrame - Set window size and position 1280x800 pos=0,0
19:31:20.454 [AWT-EventQueue-0] DEBUG c.m.r.MainWindowDropTarget - adding drag + drop support...
19:31:25.078 [AWT-EventQueue-0] INFO  c.m.r.s.r.mesh.load.MeshFactory - Loading /viewCube.obj with Wavefront Object File (OBJ)
19:31:25.090 [AWT-EventQueue-0] INFO  c.m.r.renderpanel.OpenGLRenderPanel - creating OpenGLRenderPanel
19:31:25.091 [AWT-EventQueue-0] INFO  c.m.r.renderpanel.OpenGLRenderPanel - availability=Natives[GL4bc false, GL4 true [4.1 (Core profile, arb, compat[ES2, ES3], FBO, hardware)], GLES3 false, GL3bc false, GL3 true [4.1 (Core profile, arb, compat[ES2, ES3], FBO, hardware)], GL2 true [2.1 (Compat profile, arb, compat[], FBO, hardware)], GLES2 false, GLES1 false, count 3 / 8], Common[, GL4ES3 true, GL2GL3 true, GL2ES2 true, GL2ES1 true], Mappings[GL2ES1 GLProfile[GL2ES1/GL2.hw], GL4ES3 GLProfile[GL4ES3/GL4.hw], GL2ES2 GLProfile[GL2ES2/GL4.hw], GL2 GLProfile[GL2/GL2.hw], GL4 GLProfile[GL4/GL4.hw], GL3 GLProfile[GL3/GL4.hw], GL2GL3 GLProfile[GL2GL3/GL4.hw], , default GLProfile[GL2/GL2.hw], count 7 / 12]
19:31:25.091 [AWT-EventQueue-0] INFO  c.m.r.renderpanel.OpenGLRenderPanel - ...get default caps
19:31:25.091 [AWT-EventQueue-0] INFO  c.m.r.renderpanel.OpenGLRenderPanel - ...set caps to rgba 8/8/8/1, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/8/4, sample-ext default, dbl, mono  , hw, GLProfile[GL2/GL2.hw], on-scr[.]
19:31:25.091 [AWT-EventQueue-0] INFO  c.m.r.renderpanel.OpenGLRenderPanel - ...create canvas
19:31:25.206 [AWT-EventQueue-0] DEBUG c.m.r.renderpanel.OpenGLRenderPanel - start the animation system
19:31:25.212 [AWT-EventQueue-0] INFO  c.m.robotoverlord.RobotOverlord - buildEntityManagerPanel()
19:31:25.294 [AWT-EventQueue-0] DEBUG c.m.robotoverlord.Project - Setting path to /var/root/RobotOverlord/Scene
19:31:25.349 [AWT-EventQueue-0] INFO  c.m.robotoverlord.RobotOverlord - ** READY **
```

**Comment by i-make-robots** [comment]
`GLProfile profile = GLProfile.getMaxProgrammable(true);` might work better.  OpenGLRenderPanel.java:210
